### ISSUE TITLE
java.lang.NoClassDefFoundError when using on Devices with Android 7.1.1

### ISSUE THREAD

**Issue by ChristopherGittner** [scribejava/scribejava#1006]
Hey there,

i experienced a Problem when running the current Version 8.3.0 on an Android 7.1.1 Device.
It looks like that these Devices do not come with the "java.util.Base64" Library.

My guess is that this should be detected by this Code Section here:
https://github.com/scribejava/scribejava/blob/0142ceb93648047256d57e0056554f161816c97d/scribejava-core/src/main/java/com/github/scribejava/core/base64/Base64.java#L21-L24

But the Problem seems to be that when calling the static isAvailable() Function in the "Java8Base64" class, the static final "JAVA8_BASE64" is instantiated, which might not work when Java 8 does not come with the Base 64 Parts, which in turn throws an Exception.

https://github.com/scribejava/scribejava/blob/0142ceb93648047256d57e0056554f161816c97d/scribejava-core/src/main/java/com/github/scribejava/core/base64/Java8Base64.java#L5-L6

https://github.com/scribejava/scribejava/blob/0142ceb93648047256d57e0056554f161816c97d/scribejava-core/src/main/java/com/github/scribejava/core/base64/Java8Base64.java#L18-L25

This is the Exception that is thrown:
```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
        at com.github.scribejava.java8.base64.Java8Base64.<clinit>(Java8Base64.java:5)
        at com.github.scribejava.core.base64.Java8Base64.<clinit>(Java8Base64.java:5)
        at com.github.scribejava.core.base64.Java8Base64.isAvailable(Java8Base64.java:20)
        at com.github.scribejava.core.base64.Base64.createInstance(Base64.java:22)
        at com.github.scribejava.core.base64.Base64.getInstance(Base64.java:13)
        at com.github.scribejava.core.base64.Base64.encode(Base64.java:45)
        at com.github.scribejava.core.services.HMACSha1SignatureService.doSign(HMACSha1SignatureService.java:44)
        at com.github.scribejava.core.services.HMACSha1SignatureService.getSignature(HMACSha1SignatureService.java:32)
        at com.github.scribejava.core.oauth.OAuth10aService.getSignature(OAuth10aService.java:187)
        at com.github.scribejava.core.oauth.OAuth10aService.addOAuthParams(OAuth10aService.java:95)
        at com.github.scribejava.core.oauth.OAuth10aService.prepareRequestTokenRequest(OAuth10aService.java:81)
        at com.github.scribejava.core.oauth.OAuth10aService.getRequestToken(OAuth10aService.java:39)
```

I am not sure what the correct solution to this Problem is. Maybe add an isAvailable check in the static initializer and set the static Object to null if it is not available? :-/

**Comment by kullfar** [comment]
Hi, Christopher! My fault, shame on me. Thanks for reporting that!
I think your idea with static initializer is great. I'm trying to adopt it now.
