### ISSUE TITLE
OAuth Request is incorrect

### ISSUE THREAD

**Issue by navinkumark** [scribejava/scribejava#352]
Hi,

I have tried to execute the LinkedInExample.java but its giving me the below error.

Exception in thread "main" org.scribe.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: 'Failed to validate oauth signature and token'
    at org.scribe.extractors.TokenExtractorImpl.extract(TokenExtractorImpl.java:41)
    at org.scribe.extractors.TokenExtractorImpl.extract(TokenExtractorImpl.java:27)
    at org.scribe.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:42)

Please help me how to proceed this .

**Comment by swainsitansu** [comment]
I am also facing same issue can you please tell me how to get verifier
    Scanner in = new Scanner(System.in);
    Token requestToken = serviceProvider.getRequestToken();
    System.out.println(serviceProvider.getAuthorizationUrl(requestToken));
    System.out.println("And paste the verifier here");
    System.out.print(">>");
    Verifier verifier = new Verifier(in.nextLine());

    accessToken = serviceProvider.getAccessToken(requestToken, verifier);

**Comment by kullfar** [comment]
Hi, does the example https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/TwitterExample.java help you?
