### ISSUE TITLE
Http verb PATCH is not supported

### ISSUE THREAD

**Issue by atasc** [scribejava/scribejava#568]
Making a request with Http verb PATCH generates a java.net.ProtocolException: Invalid HTTP method: PATCH

This is the code I'm trying:

...

Token accessToken = new Token(TOKEN_KEY, TOKEN_SECRET);

OAuthRequest request = new OAuthRequest(Verb.PATCH, RESOURCE_URL);
service.signRequest(accessToken, request);
Response response = request.send();

...

and this the generated exception:

Exception in thread "main" org.scribe.exceptions.OAuthConnectionException: There was a problem while creating a connection to the remote service.
    at org.scribe.model.Request.send(Request.java:70)
    at org.scribe.model.Request.send(Request.java:76)
    at io.initio.aweber.App1.main(App1.java:38)
Caused by: java.net.ProtocolException: Invalid HTTP method: PATCH
    at java.net.HttpURLConnection.setRequestMethod(HttpURLConnection.java:428)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.setRequestMethod(HttpsURLConnectionImpl.java:374)
    at org.scribe.model.Request.doSend(Request.java:102)
    at org.scribe.model.Request.send(Request.java:66)
    ... 2 more

Is there a way to make a Http PATCH request?

**Comment by fernandezpablo85** [comment]
which jdk version are you using?

**Comment by atasc** [comment]
I'm using Oracle jdk1.8.0_60 64 bit

**Comment by fernandezpablo85** [comment]
seems a won't fix, sorry

https://bugs.openjdk.java.net/browse/JDK-7016595

**Comment by kullfar** [comment]
It seems, the issue is quite outdated and not relevant to the current state of source code.
If no one interested, I will close issue in one month
