### ISSUE TITLE
Imgur example fails

### ISSUE THREAD

**Issue by Rabrg** [scribejava/scribejava#593]
Running ImgUrExample throws the following exception

```
Exception in thread "main" com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: 'OAuth Verification Failed: The consumer_key &quot;2200fe7bc74292b&quot; token &quot;&quot; combination does not exist or is not enabled.'
	at com.github.scribejava.core.extractors.TokenExtractorImpl.extract(TokenExtractorImpl.java:39)
	at com.github.scribejava.core.extractors.TokenExtractorImpl.extract(TokenExtractorImpl.java:29)
	at com.github.scribejava.core.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:58)
	at me.rabrg.imgur.ImgUrExample.main(ImgUrExample.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

It's not because the  API key and API secret are incorrect, as I've tried two different sets and both failed with that error.

**Comment by kullfar** [comment]
What is the difference between me.rabrg.imgur.ImgUrExample.main(ImgUrExample.java:29) and the original ImgUrExample.java?

**Comment by Rabrg** [comment]
Nothing besides the values of the apiKey and apiSecret variables.

The example is working for you?

**Comment by Rabrg** [comment]
Any update? If it's not happening to others I'll look into it myself

**Comment by kullfar** [comment]
Sorry, I cannot execute this example. I didn't have any user and application on ImgUr.

Try to ask the author @dwursteisen 
here this api were introduced https://github.com/scribejava/scribejava/commit/42ef871a61bfd713120285a3a0ed7810b93ddc82

And did you check what this error text from ImgUr means?
'OAuth Verification Failed: The consumer_key &quot;2200fe7bc74292b&quot; token &quot;&quot; combination does not exist or is not enabled.'

**Comment by Rabrg** [comment]
I've submitted a pull request and emailed you Imgur API credentials if you wish to test.

**Comment by dwursteisen** [comment]
ImgUr API may have been updated since my commit (4 year old :S ).

I think (even if I haven't try) that your commit should fix your issue.
