### ISSUE TITLE
Facebook Example fails with OAuthException redirect URIs don't match code":100

### ISSUE THREAD

**Issue by vinod-bb** [scribejava/scribejava#605]
I am trying to use scribe for Facebook authentication and using the example code in your code base.

Used the below URL to get code/verifier

https://www.facebook.com/dialog/oauth?granted_scopes=1&response_type=code&client_id=473486006089780&scope=email,user_about_me,user_birthday,user_location&redirect_uri=https://test.bankbazaar.com:8050/signin_social.html/

I get the below error
{"error":{"message":"Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request","type":"OAuthException","code":100,"fbtrace_id":"FXgxdS+pnYb"}}'

What I tried to debug before reaching out to you.
1. Added https to redirect uri
2. Added a forward slash / at the end of redirect uri
3. Used Escape sequence in redirect url for getting verifier/code as below
https%3A%2F%2Ftest.bankbazaar.com%3A8050%2Fsignin_social.html%2F 

Kindly suggest if I am doing anything wrong

Console output from your FacebookExample.java

=== Facebook's OAuth Workflow ===

Fetching the Authorization URL...
Got the Authorization URL!
Now go and authorize ScribeJava here:
https://www.facebook.com/v2.2/dialog/oauth?client_id=1415540682058832&redirect_uri=https%3A%2F%2Ftest.bankbazaar.com%3A8050%2Fsignin_social.html%2F
And paste the authorization code here
>>AQCRfwpqJov_A2HYl4VRYr9rHTBno3xYUFr-THbdY-2DUz-yqyp3YQx6ob2oYsbUwS_21zCof-bWWqJpwaNYvt3KwzNKFhgG6UXIW4EZEFPdRDiuXfWY1LnWJPYYgQeYfcsbS0y9OWIHhO8cXmxFGnud5fo1AfcIE-_OCxMdT2GSpxq63xFrigWzMnetmvCNZ85BMvEfIoCazVKWjrtNb00tu8H9AKQxdRuInShe2zq_EVvcl8eREEAvf65cLh0cNs7z_F9yqGGLius7phtu2kAeT8kkBJl5FG-5IbLI1fmUw8wzrfoYOOHxxiNkpxFjlHI#_=_

Trading the Request Token for an Access Token...
Exception in thread "main" com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract a token from this: '{"error":{"message":"Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request","type":"OAuthException","code":100,"fbtrace_id":"FXgxdS+pnYb"}}'
	at com.github.scribejava.core.extractors.TokenExtractor20Impl.extract(TokenExtractor20Impl.java:32)
	at com.github.scribejava.core.oauth.OAuth20ServiceImpl.getAccessToken(OAuth20ServiceImpl.java:37)
	at com.bankbazaar.oauth.FacebookExample.main(FacebookExample.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by kullfar** [comment]
Did you fix your problem somehow? Was it the bug in the ScribeJava
