### ISSUE TITLE
401 Authorization Failed

### ISSUE THREAD

**Issue by mwshubham** [scribejava/scribejava#616]
I would be very thankful if you help me a little.
Please suggest some possible cause of this:
response body: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
 <html><head>
<title>401 Authorization Required</title>
 </head><body>
<h1>Authorization Required</h1>
<p>This server could not verify that you
 are authorized to access the document
 requested.  Either you supplied the wrong
 credentials (e.g., bad password), or your
 browser doesn't understand how to supply
 the credentials required.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
 <hr>
<address>Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips mod_bwlimited/1.4 Server at 192.168.1.223 Port 80</address>
 </body></html> 

Here is my log:

 at org.scribe.extractors.TokenExtractorImpl.extract(TokenExtractorImpl.java:41)
 at org.scribe.extractors.TokenExtractorImpl.extract(TokenExtractorImpl.java:27)
at org.scribe.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:64)
 at org.scribe.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:40)
at org.scribe.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:45)
 at com.mobikul.restapidemo.MainActivity.onCreate(MainActivity.java:63)

Is this any thing to do with Timestamp or headers.

**Comment by kullfar** [comment]
Sorry, I have no idea. Looks like the problem with the server you are accessing.
And, btw, consider upgrading to the 2.x.x version of ScribeJava
