### ISSUE TITLE
Getting null pointer at org.scribe.extractors.BaseStringExtractorImpl.getSortedAndEncodedParams

### ISSUE THREAD

**Issue by thizanetti** [scribejava/scribejava#704]
I need to explicitly set a body param to null, but I get a NPE when trying to do that. Here's the call stack for it:

```
java.lang.IllegalArgumentException: Cannot encode null object
    at org.scribe.utils.Preconditions.check(Preconditions.java:84)
    at org.scribe.utils.Preconditions.checkNotNull(Preconditions.java:31)
    at org.scribe.utils.OAuthEncoder.encode(OAuthEncoder.java:30)
    at org.scribe.model.Parameter.asUrlEncodedPair(Parameter.java:23)
    at org.scribe.model.ParameterList.asFormUrlEncodedString(ParameterList.java:74)
    at org.scribe.model.ParameterList.asOauthBaseString(ParameterList.java:64)
    at org.scribe.extractors.BaseStringExtractorImpl.getSortedAndEncodedParams(BaseStringExtractorImpl.java:36)
    at org.scribe.extractors.BaseStringExtractorImpl.extract(BaseStringExtractorImpl.java:26)
    at org.scribe.oauth.OAuth10aServiceImpl.getSignature(OAuth10aServiceImpl.java:150)
    at org.scribe.oauth.OAuth10aServiceImpl.addOAuthParams(OAuth10aServiceImpl.java:75)
    at org.scribe.oauth.OAuth10aServiceImpl.signRequest(OAuth10aServiceImpl.java:126)
```

I think the solution should be to ignore/or toString() null params when trying to getSignature. 

Perhaps making BaseStringExtractorImpl.getSortedAndEncodedParam filter off any null params, what do you think?

**Comment by kullfar** [comment]
You are using very-very-very old version of ScribeJava. Please upgrade.

ps.And why do you need to "explicitly set a body param to null"? What is the case

**Comment by kullfar** [comment]
out of date
