### ISSUE TITLE
Authentication with Google fails: NoSuchElementException

### ISSUE THREAD

**Issue by gbreeze** [scribejava/scribejava#719]
Hi,

i try to bring the google example to work, but i get an NoSuchElementException at line 55:
https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/Google20Example.java#L55

```
I/System.out: And paste the authorization code here
java.util.NoSuchElementException
	at java.util.Scanner.next(Scanner.java:968)
	at java.util.Scanner.next(Scanner.java:941)
	at com.example.gperhofer.scribejavatest.MainActivity.doAuth(MainActivity.java:79)
	at com.example.gperhofer.scribejavatest.MainActivity.btnClick(MainActivity.java:40)
	at java.lang.reflect.Method.invoke(Native Method)
	at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
	at android.view.View.performClick(View.java:5198)
	at android.view.View$PerformClick.run(View.java:21147)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Environment:
Android Studio, API Level 23

Maybe someone can help, thanks!

**Comment by kullfar** [comment]
Did you try to run the example from the console?
Example expects you input from console.
It shows url to visit and then wait for code you will get in the browser.

ps.maybe this issue will help you https://github.com/scribejava/scribejava/issues/647

**Comment by gbreeze** [comment]
Hi Stas,
thanks for clarification!

I thought i can use your simple library for my android application, but now i think i have to use the https://github.com/openid/AppAuth-Android lib for that.

**Comment by kullfar** [comment]
It's up to you ;-)
There a lot of Android usaged of ScribeJava

**Comment by gbreeze** [comment]
Nice, https://github.com/VictorAlbertos/RxSocialConnect-Android for example.
Thanks!
