### ISSUE TITLE
The provided request must be sent using the HTTP 'POST' method.

### ISSUE THREAD

**Issue by TheFuckingMaster** [scribejava/scribejava#720]
Hi, just trying OOTB LiveExample, this is the output:

Trading the Request Token for an Access Token...
Exception in thread "main" com.github.scribejava.core.model.OAuth2AccessTokenErrorResponse: {"error":"invalid_request","error_description":"The provided request must be sent using the HTTP 'POST' method."}
	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.generateError(OAuth2AccessTokenJsonExtractor.java:65)
	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.extract(OAuth2AccessTokenJsonExtractor.java:46)
	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.extract(OAuth2AccessTokenJsonExtractor.java:16)
	at com.github.scribejava.core.oauth.OAuth20Service.sendAccessTokenRequestSync(OAuth20Service.java:37)
	at com.github.scribejava.core.oauth.OAuth20Service.getAccessToken(OAuth20Service.java:56)
	at com.spamphobia.oauth.LiveExample.main(LiveExample.java:50)

After checking Live API at https://msdn.microsoft.com/en-us/library/hh243647.aspx I believe: 
com.github.scribejava.apis. LiveApi. getAccessTokenVerb() should look like:

    @Override
    public Verb getAccessTokenVerb() {
        return Verb.POST;
    }

What do you think?

**Comment by kullfar** [comment]
Seems, can be fixed here
https://github.com/scribejava/scribejava/pull/721
