### ISSUE TITLE
oauth_verifier in the body instead of the header ?

### ISSUE THREAD

**Issue by jpv** [scribejava/scribejava#727]
The example doesn't work for me.
the oauth_verifier must be in the header not in the body.
Twitter doc seems out of date.
see https://twittercommunity.com/t/invalid-oauth-verifier-parameter/38724/2

..... Running the example 
Trading the Request Token for an Access Token...
Exception in thread "main" com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: '**Error processing your OAuth request: Invalid oauth_verifier parameter**'
        at com.github.scribejava.core.extractors.AbstractOAuth1TokenExtractor.extract(AbstractOAuth1TokenExtractor.java:42)
        at com.github.scribejava.core.extractors.AbstractOAuth1TokenExtractor.extract(AbstractOAuth1TokenExtractor.java:32)
        at com.github.scribejava.core.extractors.AbstractOAuth1TokenExtractor.extract(AbstractOAuth1TokenExtractor.java:19)
        at com.github.scribejava.core.oauth.OAuth10aService.getAccessToken(OAuth10aService.java:100)

**Comment by kullfar** [comment]
Did you solve your issue? Some hints. May be it will be helpful to someone in the future

**Comment by jpv** [comment]
Not an issue. I made a big mistake... Shame on me.

**Comment by bruno-vieira-emix** [comment]
Qual era o problema ?

**Comment by Wsupatgiat** [comment]
What mistake did you make? I've been getting the same error and I can't seem to find where I might went wrong.
