### ISSUE TITLE
Error extraction does not work for Facebook OAuth2

### ISSUE THREAD

**Issue by everflux** [scribejava/scribejava#736]
When using Facebook Login with an invalid token the error message is not correctly extracted, I assume this is due to using a regex while Facebook sends a JSON encoded error object.

```
nested exception is com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract a '"error"\s*:\s*"(\S*?)"' from this: '{"error":{"message":"This authorization code has been used.","type":"OAuthException","code":100,"fbtrace_id":"ASQD20TV65c"}}'] with root cause
com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract a '"error"\s*:\s*"(\S*?)"' from this: '{"error":{"message":"This authorization code has been used.","type":"OAuthException","code":100,"fbtrace_id":"ASQD20TV65c"}}'
 	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.extractParameter(OAuth2AccessTokenJsonExtractor.java:97) ~[scribejava-core-3.4.1.jar!/:na]
 	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.generateError(OAuth2AccessTokenJsonExtractor.java:55) ~[scribejava-core-3.4.1.jar!/:na]
 	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.extract(OAuth2AccessTokenJsonExtractor.java:46) ~[scribejava-core-3.4.1.jar!/:na]
```

**Comment by kullfar** [comment]
Thanks for report. I will try to fix that a bit later

**Comment by kullfar** [comment]
Have fixed

https://github.com/scribejava/scribejava/commit/caf723056f41fc0561719f2b24856eb58515b13f
code in the master. going to the maven central in couple of hours

**Comment by everflux** [comment]
Thank you!
