### ISSUE TITLE
Guide to add new API provider

### ISSUE THREAD

**Issue by Mdhaker** [scribejava/scribejava#771]
Hello,
If I want to add instagram API which i think is not supported yet, is there a simple way to do it ? if you consider the scribe solution is generic somehow what should I do to add a new API provider.
creating a class that extends DefaultAPI is enough ?

**Comment by kullfar** [comment]
Hi,
you can find answers here
https://github.com/scribejava/scribejava/wiki

**Comment by Mdhaker** [comment]
The guide i found in the documentation if for OAuth1, I'm trying to implement a client for Instagram which uses OAuth2.0, Here is my code : 
Note : its juste an inside class that's why it's private, I call its instance through the parent class.
> private static class InstagramApi extends DefaultApi20
	{
	    private static final InstagramApi INSTANCE = new InstagramApi();

	    public static InstagramApi instance() {
	        return INSTANCE;
	    }
	    @Override
	    public Verb getAccessTokenVerb() {
	        return Verb.GET;
	    }
		@Override
		public String getAccessTokenEndpoint() {
			return "https://api.instagram.com/oauth/access_token";
		}

		@Override
		protected String getAuthorizationBaseUrl() {
			return "https://api.instagram.com/oauth/authorize/";
		}
		
	}

this is the error i got when i tried to sign the request : 

> Exception in thread "main" java.lang.IllegalArgumentException: Cannot get String from a null object
	at com.github.scribejava.core.utils.Preconditions.check(Preconditions.java:71)
	at com.github.scribejava.core.utils.Preconditions.checkNotNull(Preconditions.java:26)
	at com.github.scribejava.core.utils.StreamUtils.getStreamContents(StreamUtils.java:22)
	at com.github.scribejava.core.model.Response.parseBodyContents(Response.java:44)
	at com.github.scribejava.core.model.Response.getBody(Response.java:62)
	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.extract(OAuth2AccessTokenJsonExtractor.java:41)
	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.extract(OAuth2AccessTokenJsonExtractor.java:16)
	at com.github.scribejava.core.oauth.OAuth20Service.sendAccessTokenRequestSync(OAuth20Service.java:37)
	at com.github.scribejava.core.oauth.OAuth20Service.getAccessToken(OAuth20Service.java:56)
	at com.datacollection.utils.Auth.getUserAccessToken(Auth.java:198)
	at com.datacollection.services.InstagramAPI.getUser(InstagramAPI.java:40)
	at com.datacollection.config.App.main(App.java:21)

**Comment by kullfar** [comment]
And what is the code you run? Does it work for another APIs?

**Comment by Mdhaker** [comment]
I found an Instagram sample implemented by one of the guys here and it works fine, I will use it.
Thank you.
