### ISSUE TITLE
Android Nougat API 24 java.lang.ClassNotFoundException: Didn't find class "java.util.Base64" 

### ISSUE THREAD

**Issue by graves501** [scribejava/scribejava#813]
First of all thanks for all your efforts, this library is great!

I tested the 5.0.0 version with Android API 26 (Oreo) and it works like a charm, but once I run it with API 24 (Nougat) it throws these errors.

For now my solution is to downgrade to 4.2.0 so I can use the library with API 24!

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: seam.creative.com.seamandroid, PID: 10053
                  java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
                      at com.github.scribejava.core.pkce.PKCEService.<clinit>(PKCEService.java:14)
                      at com.github.scribejava.core.oauth.OAuth20Service.<clinit>(OAuth20Service.java:26)
                      at com.github.scribejava.core.builder.api.DefaultApi20.createService(DefaultApi20.java:103)
                      at com.github.scribejava.core.builder.api.DefaultApi20.createService(DefaultApi20.java:26)
                      at com.github.scribejava.core.builder.ServiceBuilder.build(ServiceBuilder.java:141)
                      at seam.creative.com.seamandroid.oauth2.OAuthServiceInstance.<clinit>(OAuthServiceInstance.java:10)
                      at seam.creative.com.seamandroid.oauth2.OAuthServiceInstance.getInstance(OAuthServiceInstance.java:0)
                      at seam.creative.com.seamandroid.SignInActivity.onCreate(SignInActivity.java:36)
                      at android.app.Activity.performCreate(Activity.java:6662)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Base64" on path: DexPathList[[zip file "/data/app/seam.creative.com.seamandroid-2/base.apk", zip file "/data/app/seam.creative.com.seamandroid-2/split_lib_dependencies_apk.apk", zip file "/data/app/seam.creative.com.seamandroid-2/split_lib_slice_0_apk.apk", zip file "/data/app/seam.creative.com.seamandroid-2/split_lib_slice_1_apk.apk", zip file "/data/app/seam.creative.com.seamandroid-2/split_lib_slice_2_apk.apk", zip file "/data/app/seam.creative.com.seamandroid-2/split_lib_slice_3_apk.apk", zip file "/data/app/seam.creative.com.seamandroid-2/split_lib_slice_4_apk.apk", zip file "/data/app/seam.creative.com.seamandroid-2/split_lib_slice_5_apk.apk", zip file "/data/app/seam.creative.com.seamandroid-2/split_lib_slice_6_apk.apk", zip file "/data/app/seam.creative.com.seamandroid-2/split_lib_slice_7_apk.apk", zip file "/data/app/seam.creative.com.seamandroid-2/split_lib_slice_8_apk.apk", zip file "/data/app/seam.creative.com.seamandroid-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/seam.creative.com.seamandroid-2/lib/x86, /system/lib, /vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at com.github.scribejava.core.pkce.PKCEService.<clinit>(PKCEService.java:14) 
                      at com.github.scribejava.core.oauth.OAuth20Service.<clinit>(OAuth20Service.java:26) 
                      at com.github.scribejava.core.builder.api.DefaultApi20.createService(DefaultApi20.java:103) 
                      at com.github.scribejava.core.builder.api.DefaultApi20.createService(DefaultApi20.java:26) 
                      at com.github.scribejava.core.builder.ServiceBuilder.build(ServiceBuilder.java:141) 
                      at seam.creative.com.seamandroid.oauth2.OAuthServiceInstance.<clinit>(OAuthServiceInstance.java:10) 
                      at seam.creative.com.seamandroid.oauth2.OAuthServiceInstance.getInstance(OAuthServiceInstance.java:0) 
                      at seam.creative.com.seamandroid.SignInActivity.onCreate(SignInActivity.java:36) 
                      at android.app.Activity.performCreate(Activity.java:6662) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6077) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) `

**Comment by kullfar** [comment]
I think, it's about drop of java7 support.
https://github.com/scribejava/scribejava/issues/807
I'll return it soon

**Comment by kullfar** [comment]
ready.
ScribeJava is java7-compatible again.
v.5.2.0-java7again
Can you test your problem with this version?

**Comment by graves501** [comment]
@kullfar thx for fixing this issue! since I already found an alternative to this library, I won't be able to test it anytime soon. Maybe I will test it in my freetime with my own project. I'll let you know.
