### ISSUE TITLE
Cannot encode null object in new API

### ISSUE THREAD

**Issue by bknill** [scribejava/scribejava#819]
Hey, 

I think this is a common issue - and I can see lots of solutions for twitter but nothing for my case. I'm trying to implement a simple api that has no access key,

> The API is secured with OAuth 1.0a. You must use your client key and secret to sign requests when accessing the API. There are many established libraries that will take care of authenticating calls for you. There is no need to provide an access token as our API endpoints do not yet support granting access to a users private data. 

I've tried setting up my own custom API

```
public class NounProjectApi extends DefaultApi10a {
	private static final String AUTHORIZE_URL = "http://api.thenounproject.com/icon/1";

	protected NounProjectApi() {
	}

	private static class InstanceHolder {
		private static final NounProjectApi INSTANCE = new NounProjectApi();
	}

	public static NounProjectApi instance() {
		return InstanceHolder.INSTANCE;
	}

	@Override
	public String getAccessTokenEndpoint(){
		return "http://api.thenounproject.com/icon/1";
	}

	@Override
	public String getRequestTokenEndpoint() {
		return "http://api.thenounproject.com/icon/1";
	}

	@Override
	public String getAuthorizationUrl(OAuth1RequestToken requestToken) {
		return String.format(AUTHORIZE_URL, requestToken.getToken());
	}
}
```

But it always fails on final OAuth1RequestToken requestToken = service.getRequestToken();

With the error: 

```
Caused by: java.lang.IllegalArgumentException: Cannot encode null object
	at com.github.scribejava.core.utils.Preconditions.check(Preconditions.java:49)
	at com.github.scribejava.core.utils.Preconditions.checkNotNull(Preconditions.java:19)
	at com.github.scribejava.core.utils.OAuthEncoder.encode(OAuthEncoder.java:26)
	at com.github.scribejava.core.model.Parameter.asUrlEncodedPair(Parameter.java:16)
	at com.github.scribejava.core.model.ParameterList.asFormUrlEncodedString(ParameterList.java:63)
	at com.github.scribejava.core.model.ParameterList.asOauthBaseString(ParameterList.java:53)
	at com.github.scribejava.core.extractors.BaseStringExtractorImpl.getSortedAndEncodedParams(BaseStringExtractorImpl.java:41)
	at com.github.scribejava.core.extractors.BaseStringExtractorImpl.extract(BaseStringExtractorImpl.java:24)
	at com.github.scribejava.core.oauth.OAuth10aService.getSignature(OAuth10aService.java:169)
	at com.github.scribejava.core.oauth.OAuth10aService.addOAuthParams(OAuth10aService.java:88)
	at com.github.scribejava.core.oauth.OAuth10aService.prepareRequestTokenRequest(OAuth10aService.java:72)
	at com.github.scribejava.core.oauth.OAuth10aService.getRequestToken(OAuth10aService.java:39)
	at co.beek.pano.service.restService.SocialRestController.getNounProjectIcon(SocialRestController.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Any clues on what I'm missing!?

**Comment by bknill** [comment]
I added a callback and it's getting closer..

Now it can't get the token

```
javax.servlet.ServletException: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.</p><p>If you entered the URL manually please check your spelling and try again.</p>
'
```

Now I assume it's because of this not needing an access key but still need to sign requests. 

Is scribeJava the right library for this?

**Comment by kullfar** [comment]
"There is no need to provide an access token as our API endpoints do not yet support granting access to a users private data."
rather bad practice. OAuth standard have client credenitals grant flow for that case.

404 means you provided a wrong url/verb in your Api class. Looks like this.
anyway I need a code that you are invoking while getting this response

**Comment by kullfar** [comment]
rather bad practice. OAuth standard have client credenitals grant flow for that case.

404 means you provided a wrong url/verb in your Api class. Looks like this.
anyway I need a code that you are invoking while getting this response

**Comment by bknill** [comment]
Thanks for getting back to me. 

This is where I got to - just trying anything at the moment to get it to work!

```
			final OAuth10aService service = new ServiceBuilder("dec8dd2ae39246d0acacb111129ef222")
					.apiSecret("0170285ad8e1439a9f14554f250a35bc")
                    .callback("http://api.thenounproject.com/icon/1")
					.build(NounProjectApi.instance());

			final OAuth1RequestToken requestToken = service.getRequestToken();
```

```
`public class NounProjectApi extends DefaultApi10a {
	private static final String AUTHORIZE_URL = "http://api.thenounproject.com/icon/1";

	protected NounProjectApi() {
	}

	private static class InstanceHolder {
		private static final NounProjectApi INSTANCE = new NounProjectApi();
	}

	public static NounProjectApi instance() {
		return InstanceHolder.INSTANCE;
	}

	@Override
	public String getAccessTokenEndpoint(){
		return "http://api.thenounproject.com/icon/1";
	}

	@Override
	public String getRequestTokenEndpoint() {
		return "http://api.thenounproject.com/icon/1";
	}

	@Override
	public String getAuthorizationUrl(OAuth1RequestToken requestToken) {
		return String.format(AUTHORIZE_URL, requestToken.getToken());
	}
}`
```

**Comment by bknill** [comment]
Kind of got it working with

	@Override
	public Verb getRequestTokenVerb()
	{
		return Verb.GET;
	}

But it's getting upset with the response (which is what I"m looking for)

```
HTTP ERROR 500
Problem accessing /icon/hello. Reason:

    Server Error
Caused by:
javax.servlet.ServletException: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: '{
  "icon": {
    "attribution": "Trash from Noun Project", 
    "collections": [
      {
        "author": {
          "location": "Los Angeles, US", 
          "name": "Edward Boatman", 
          "permalink": "/edward", 
          "username": "edward"
        }, 
        "author_id": "6", 
        "date_created": "2012-01-27 19:15:26", 
        "date_updated": "2012-09-27 13:27:02", 
        "description": "", 
        "id": "3", 
        "is_collaborative": "", 
        "is_featured": "1", 
        "is_published": "1", 
        "is_store_item": "0", 
        "name": "AIGA", 
        "permalink": "/edward/collection/aiga", 
        "slug": "aiga", 
        "sponsor": {}, 
        "sponsor_campaign_link": "", 
        "sponsor_id": "", 
        "tags": [], 
        "template": "24"
      }
    ], 
    "date_uploaded": "", 
    "icon_url": "https://d30y9cdsu7xlg0.cloudfront.net/noun-svg/1.svg?Expires=1517461918&Signature=MvxzV89F9yZxhfq1Th4z1aXJWQX2Ox84dMq8ggHxkfQTXYa1Dam-RBg82O4rymJlDVbYLgn5G6RaMmWqu8-d2u06GgYsbPTTypj8uAv8JozBSUphqAwTT82cHFgZqff4tJ4yt98BYkgoxjl1i8nZxXM4baM29F45EIOoSXGhYZ8_&Key-Pair-Id=APKAI5ZVHAXN65CHVU2Q", 
    "id": "1", 
    "is_active": "1", 
    "is_explicit": "0", 
    "license_description": "public-domain", 
    "nounji_free": "0", 
    "permalink": "/term/trash/1", 
    "preview_url": "https://d30y9cdsu7xlg0.cloudfront.net/png/1-200.png", 
    "preview_url_42": "https://d30y9cdsu7xlg0.cloudfront.net/png/1-42.png", 
    "preview_url_84": "https://d30y9cdsu7xlg0.cloudfront.net/png/1-84.png", 
    "sponsor": {}, 
    "sponsor_campaign_link": null, 
    "sponsor_id": "", 
    "tags": [
      {
        "id": 19, 
        "slug": "trash"
      }, 
      {
        "id": 20, 
        "slug": "garbage"
      }, 
      {
        "id": 1974, 
        "slug": "trash-can"
      }, 
      {
        "id": 11120, 
        "slug": "throw-away"
      }
    ], 
    "term": "Trash", 
    "term_id": 19, 
    "term_slug": "trash", 
    "uploader": {}, 
    "uploader_id": "", 
    "year": 1974
  }
}
'
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:565)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:231)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:123)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:232)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: '{

```

How do I get it to accept this response?

**Comment by bknill** [comment]
Annoyingly I can get the data I want from 

catch (OAuthException e) {
		    String result = e.getMessage();

But I can't pass in the URL parameter into determine the search

**Comment by kullfar** [comment]
You said you don't need the token, what for are you invoking this method service.getRequestToken()?
You need just signing the request.
You mustn't try to parse tokens from data response.

Looks like you have signed the token request, but have used URL and VERB for getting some data, not token.
Use url for token to get token and invoke method to get token.
Or use url for data and invoke method to get data and do not parse it to get token from it.

**Comment by bknill** [comment]
Sorry thanks for your help, I'm totally confused by this. I can't find any other examples in the library where you don't need the token..

So to sign the request, you need the access token, and to get that you need the request token right? 

How can I use the URL just to get data, without trying to parse a token? Is there a function that just calls the data with the parameters? 

```
			final OAuth1RequestToken requestToken = service.getRequestToken();
			String authUrl = service.getAuthorizationUrl(requestToken);
			final OAuth1AccessToken accessToken = service.getAccessToken(requestToken, "verifier you got from the user/callback");
			final OAuthRequest request = new OAuthRequest(Verb.GET, "http://api.thenounproject.com/icon/" + search);

			service.signRequest(accessToken, request); // the access token from step 4
			final Response response = service.execute(request);
```

I tried just executing the request and I get a no params error 

> `<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>400 Bad Request</title>\n<h1>Bad Request</h1>\nMissing OAuth parameters\n"`

Could you explain to me how I use the url to get data and avoid parsing it? Is there a different function I should be using just to get the data?

**Comment by kullfar** [comment]
As I understood, you need not to 'sign by token', but 'sign by client key and secret' like it is in the 'get request token' request itself as well.
You wrote before: "You must use your client key and secret to sign requests when accessing the API."
Only this part of signing.

Look at methods appendSignature, getSignature from OAuth10aService, SignatureService interface and it's implementations, usages of OAuthConfig.getApiSecret method to see where secret key can be used.

It's not standard usages, so you have to investigate a bit.

May be you will need some private methods to become public, let me know if it's the case.

**Comment by bknill** [comment]
Thanks @kullfar,

I used Signpost in the end, I got this working quite easily for this use case.  They tried to make this API very simple and it became very complicated!
