### ISSUE TITLE
OAuth20Service not able to handle client id

### ISSUE THREAD

**Issue by ElitekrishnaRao** [scribejava/scribejava#827]
OAuth20Service :- utilized the same code provided in ur examples.(	private static final String PROTECTED_RESOURCE_URL = "https://api.linkedin.com/v2/me";)

**Error log:-**
=== LinkedIn's OAuth Workflow ===

Fetching the Authorization URL...
Got the Authorization URL!
Now go and authorize ScribeJava here:
https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=81tqxy39bxxi4s&redirect_uri=https%3A%2F%2Fwww.google.co.in&scope=r_basicprofile
And paste the authorization code here
>>AQSYwvxBuZuUd__qTmgEdmcg4bd4uqmDSN2DtrM77Vpe15E2ZLVMtNDqrbHVJwkzqf-w07c6F983okltNRjy8nxzlKyGAi-0GhPwzVTHV0mXPqgXW-QIQpZOm-UEivfOzEOm72m_OArF8xJqyMPB0Ukfc2aqXQ

Trading the Request Token for an Access Token...
Exception in thread "main" com.github.scribejava.core.model.OAuth2AccessTokenErrorResponse: {"error":"invalid_request","error_description":"A required parameter \"client_id\" is missing"}
	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.generateError(OAuth2AccessTokenJsonExtractor.java:67)
	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.extract(OAuth2AccessTokenJsonExtractor.java:46)
	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.extract(OAuth2AccessTokenJsonExtractor.java:16)
	at com.github.scribejava.core.oauth.OAuth20Service.sendAccessTokenRequestSync(OAuth20Service.java:43)
	at com.github.scribejava.core.oauth.OAuth20Service.getAccessToken(OAuth20Service.java:75)
	at com.github.scribejava.core.oauth.OAuth20Service.getAccessToken(OAuth20Service.java:68)
	at com.linkedin.messaging.LinkedInTest.main(LinkedInTest.java:64)

**Comment by kullfar** [comment]
Do you need any help?
What is the version of ScribeJava you are using?

**Comment by ElitekrishnaRao** [comment]
5.0.0 API one and core one also.

**Comment by kullfar** [comment]
try >= 5.1.0
it has fix
 * fix LinkedInApi20 (thanks to https://github.com/jhorowitz-firedrum)
(c) https://github.com/scribejava/scribejava/blob/master/changelog

**Comment by ElitekrishnaRao** [comment]
K thanks

**Comment by kullfar** [comment]
Can we close the issue? No more quiestions?

**Comment by ElitekrishnaRao** [comment]
Yes please
