### ISSUE TITLE
How to use OkHttpClient with TwitterExample?

### ISSUE THREAD

**Issue by eos1d3** [scribejava/scribejava#845]
I modified the TwitterExample to try OkHttpClient as below:

```
import com.github.scribejava.apis.TwitterApi;
import com.github.scribejava.core.builder.ServiceBuilder;
import com.github.scribejava.core.model.OAuth1AccessToken;
import com.github.scribejava.core.model.OAuthRequest;
import com.github.scribejava.core.model.Response;
import com.github.scribejava.core.model.Verb;
import com.github.scribejava.core.oauth.OAuth10aService;
import com.github.scribejava.httpclient.okhttp.OkHttpHttpClientConfig;
import okhttp3.OkHttpClient;
import java.io.IOException;
import java.util.concurrent.ExecutionException;

public final class TwitterExample {
	private static final String PROTECTED_RESOURCE_URL = "https://api.twitter.com/1.1/account/verify_credentials.json";

	public static void main(String... args) throws IOException, InterruptedException, ExecutionException {
		final OkHttpClient.Builder okHttpBuilder = new OkHttpClient.Builder();

		final OAuth10aService service = new ServiceBuilder("xxxxxxxxxxxxxx")
			.httpClientConfig(new OkHttpHttpClientConfig(okHttpBuilder))
			.apiSecret("yyyyyyyyyyyy").build(TwitterApi.instance());

		final OAuth1AccessToken accessToken = new OAuth1AccessToken(
			"zzzzzzzzzzzzzzz", 
			"ppppppppppppppp");

		System.out.println("Now we're going to access a protected resource...");
		final OAuthRequest request = new OAuthRequest(Verb.GET, PROTECTED_RESOURCE_URL);
		service.signRequest(accessToken, request);
		final Response response = service.execute(request);

		System.out.println(response.getBody());
	}
}
```

It works without the above `.httpClientConfig`, with it I always get exception below:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/scribejava/httpclient/okhttp/OkHttpHttpClientConfig
	at scribejava.TwitterExample.main(TwitterExample.java:27)
Caused by: java.lang.ClassNotFoundException: com.github.scribejava.httpclient.okhttp.OkHttpHttpClientConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

```

The dependencies are:
```
<dependency>
	<groupId>com.github.scribejava</groupId>
	<artifactId>scribejava-apis</artifactId>
	<version>5.0.0</version>
</dependency>

<dependency>
	<groupId>com.github.scribejava</groupId>
	<artifactId>scribejava-httpclient-okhttp</artifactId>
	<version>5.3.0</version>
	<scope>test</scope>
</dependency>

<dependency>
	<groupId>com.squareup.okhttp3</groupId>
	<artifactId>okhttp</artifactId>
	<version>3.10.0</version>
</dependency>

```

So what am I missing?

**Comment by kullfar** [comment]
Are you running this Example as test? via 'mvn test'?
otherwise try to remove <scope>test</scope> from the dependency

**Comment by eos1d3** [comment]
No, I do not use test. I run it in Eclipse. As you can see the main method is there. The above is the whole program. 

Without `.httpClientConfig(new OkHttpHttpClientConfig(okHttpBuilder))
` it can work with default httpclient (JDK http client), I can see the JSON response.

**Comment by danmana** [comment]
Like @kullfar mentioned, you should remove the `<scope>test</scope>` from the `scribejava-httpclient-okhttp` dependency.

Also, there is no need to import okhttp separatly, it is a transitive dependency of `scribejava-httpclient-okhttp`, and you should use the same version for  `scribejava-api` and  `scribejava-httpclient-okhttp`.

Your dependencies should be:
```
<dependencies>

        <dependency>
            <groupId>com.github.scribejava</groupId>
            <artifactId>scribejava-apis</artifactId>
            <version>5.4.0</version>
        </dependency>

        <dependency>
            <groupId>com.github.scribejava</groupId>
            <artifactId>scribejava-httpclient-okhttp</artifactId>
            <version>5.4.0</version>
        </dependency>

    </dependencies>
```

**Comment by eos1d3** [comment]
Problem solved. 
Thank you!
