### ISSUE TITLE
"Cannot encode null object" error

### ISSUE THREAD

**Issue by Rafaelsk** [scribejava/scribejava#846]
After running the Twitter example I get the following exception + stacktrace:

```console
=== Twitter's OAuth Workflow ===

Fetching the Request Token...
Exception in thread "main" java.lang.IllegalArgumentException: Cannot encode null object
	at com.github.scribejava.core.utils.Preconditions.check(Preconditions.java:49)
	at com.github.scribejava.core.utils.Preconditions.checkNotNull(Preconditions.java:19)
	at com.github.scribejava.core.utils.OAuthEncoder.encode(OAuthEncoder.java:26)
	at com.github.scribejava.core.model.Parameter.asUrlEncodedPair(Parameter.java:16)
	at com.github.scribejava.core.model.ParameterList.asFormUrlEncodedString(ParameterList.java:63)
	at com.github.scribejava.core.model.ParameterList.asOauthBaseString(ParameterList.java:53)
	at com.github.scribejava.core.extractors.BaseStringExtractorImpl.getSortedAndEncodedParams(BaseStringExtractorImpl.java:41)
	at com.github.scribejava.core.extractors.BaseStringExtractorImpl.extract(BaseStringExtractorImpl.java:24)
	at com.github.scribejava.core.oauth.OAuth10aService.getSignature(OAuth10aService.java:168)
	at com.github.scribejava.core.oauth.OAuth10aService.addOAuthParams(OAuth10aService.java:87)
	at com.github.scribejava.core.oauth.OAuth10aService.prepareRequestTokenRequest(OAuth10aService.java:71)
	at com.github.scribejava.core.oauth.OAuth10aService.getRequestToken(OAuth10aService.java:39)
	at de.liquidlabs.fuhlsbuettel.controller.TwitterExample.main(TwitterExample.java:30)
```

After looking at the source code it looks like it's because the callback url is not provided and there's a null check for it.

**Comment by Rafaelsk** [comment]
### Update
It worked after adding the callback value to the builder:
```java
final OAuth10aService service = new ServiceBuilder("tpMfYuiCj8NEBbf6pbvFfm4Zd")
                .apiSecret("5mH1lgxgAumbGChhpeUKw5euPL6GnSmW3P7zzK3XzkcQZYu3sd")
                .callback("oob")
                .build(TwitterApi.instance());
        final Scanner in = new Scanner(System.in);
```

**Comment by kullfar** [comment]
thanks, will fix tomorrow

**Comment by kullfar** [comment]
done
https://github.com/scribejava/scribejava/commit/03dd1eafd8bc9bb3861e0195f93d72b93ab272c8

**Comment by kullfar** [comment]
be aware of some refactoring before this commit
https://github.com/scribejava/scribejava/commit/aec994745985ef4b8e2fa2db7f2f20f3d5349186
