### ISSUE TITLE
Exception in thread "main" com.github.scribejava.core.model.OAuth2AccessTokenErrorResponse: {"error":"invalid_redirect_uri","error_description":"Unable to retrieve access token: appid/redirect uri/code verifier does not match authorization code. Or authorization code expired. Or external member binding exists"}

### ISSUE THREAD

**Issue by vayouva** [scribejava/scribejava#848]
Hi kullfar, 

I just tried LinkedIn20Example on my machine and I got this error :( 

`=== LinkedIn's OAuth Workflow ===

Fetching the Authorization URL...
Got the Authorization URL!
Now go and authorize ScribeJava here:
https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=78as3jzx478svw&redirect_uri=http%3A%2F%2Fexample.com%2Fcallback&scope=r_basicprofile%20r_emailaddress&state=some_params
And paste the authorization code here
>>https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=78as3jzx478svw&redirect_uri=http%3A%2F%2Fexample.com%2Fcallback&scope=r_basicprofile%20r_emailaddress&state=some_params

Trading the Request Token for an Access Token...
Exception in thread "main" com.github.scribejava.core.model.OAuth2AccessTokenErrorResponse: {"error":"invalid_redirect_uri","error_description":"Unable to retrieve access token: appid/redirect uri/code verifier does not match authorization code. Or authorization code expired. Or external member binding exists"}
	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.generateError(OAuth2AccessTokenJsonExtractor.java:75)
	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.extract(OAuth2AccessTokenJsonExtractor.java:46)
	at com.github.scribejava.core.extractors.OAuth2AccessTokenJsonExtractor.extract(OAuth2AccessTokenJsonExtractor.java:16)
	at com.github.scribejava.core.oauth.OAuth20Service.sendAccessTokenRequestSync(OAuth20Service.java:62)
	at com.github.scribejava.core.oauth.OAuth20Service.getAccessToken(OAuth20Service.java:98)
	at com.github.scribejava.core.oauth.OAuth20Service.getAccessToken(OAuth20Service.java:91)
	at com.sinay.Main.main(Main.java:103)`

Can you help me with this issue please ? 
Thank you :)

**Comment by kullfar** [comment]
Did you paste "the authorization code" to the console?

**Comment by kullfar** [comment]
nope. code and url is not the same.
you should open url in your browser and then copy paste the code from the back url

**Comment by vayouva** [comment]
I did it, but the browser shows me this error : The redirect_uri does not match the registered value.

**Comment by kullfar** [comment]
You got all info you need. you should sync redirect_uri in Auth Url and in App settings

**Comment by vayouva** [comment]
I think that I miss something in the App settings too, I'm going to check this out ;) Thanks

**Comment by kullfar** [comment]
note ```&state=some_params``` in code you mentioned.

**Comment by vayouva** [comment]
It worked finally 👍 can you tell me, can you tell me if it is possible to use such program to get email addresses of employees of a specified company? 
The only data I get here is mine :)

**Comment by kullfar** [comment]
It's out-of-scope question. You should consult LinkedIn API, not ScribeJava

**Comment by kullfar** [comment]
welcome

**Comment by vayouva** [comment]
Thank you
