### ISSUE TITLE
IllegalArgumentException: Cannot encode null object when redirectUrl not set

### ISSUE THREAD

**Issue by computerlove** [scribejava/scribejava#870]
Is redirecturl a required config?
In our setup it is configured on the server for the given clientid, so it should not be necessary to specify it when getting authorization token from a code.

Stacktrace:
```
java.lang.IllegalArgumentException: Cannot encode null object
	at com.github.scribejava.core.utils.Preconditions.check(Preconditions.java:49)
	at com.github.scribejava.core.utils.Preconditions.checkNotNull(Preconditions.java:19)
	at com.github.scribejava.core.utils.OAuthEncoder.encode(OAuthEncoder.java:26)
	at com.github.scribejava.core.model.Parameter.asUrlEncodedPair(Parameter.java:16)
	at com.github.scribejava.core.model.ParameterList.asFormUrlEncodedString(ParameterList.java:63)
	at com.github.scribejava.core.model.OAuthRequest.getByteArrayPayload(OAuthRequest.java:232)
	at com.github.scribejava.core.oauth.OAuthService.execute(OAuthService.java:127)
	at com.github.scribejava.core.oauth.OAuth20Service.sendAccessTokenRequestSync(OAuth20Service.java:57)
	at com.github.scribejava.core.oauth.OAuth20Service.getAccessToken(OAuth20Service.java:93)
	at com.github.scribejava.core.oauth.OAuth20Service.getAccessToken(OAuth20Service.java:86)
	at no.vegvesen.forvaltning.web.resources.AuthResource.callback(AuthResource.java:44)
```

**Comment by kullfar** [comment]
It depends on Flow you are using.
In case of common "Authorization Code Grant" (exchange code for Access Token), it's 
```
REQUIRED, if the "redirect_uri" parameter was included in the
         authorization request as described in Section 4.1.1, and their
         values MUST be identical.
```
(c) https://tools.ietf.org/html/rfc6749#section-4.1.3

But it's just standard. OAuth provider can decide smth else ;-)

**Comment by computerlove** [comment]
Ok. I added PR 871 for a null check before adding callback url to parameters

**Comment by kullfar** [comment]
fixed in https://github.com/scribejava/scribejava/pull/871
