### ISSUE TITLE
Scribe java Apache HTTP client unable to handle 204(NO_CONTENT) HTTP Status code

### ISSUE THREAD

**Issue by SainagNeelamPatnaik** [scribejava/scribejava#896]
Hi, I am poor in English. please ignore if any typo errors. :)  
I am getting some problem to handle API response with HTTP Status code 204 and which doesn't contains the body or entity. So i am getting below exception trace in API invocation result.  
```java.util.concurrent.ExecutionException: java.lang.NullPointerException
               at com.github.scribejava.httpclient.apache.OAuthAsyncCompletionHandler.getResult(OAuthAsyncCompletionHandler.java:91)
               at com.github.scribejava.httpclient.apache.ApacheHttpFuture.get(ApacheHttpFuture.java:37)
               at com.github.scribejava.core.httpclient.AbstractAsyncOnlyHttpClient.execute(AbstractAsyncOnlyHttpClient.java:47)
               at com.github.scribejava.core.oauth.OAuthService.execute(OAuthService.java:111)
               ...............................................
Caused by: java.lang.NullPointerException: null
               at com.github.scribejava.httpclient.apache.OAuthAsyncCompletionHandler.completed(OAuthAsyncCompletionHandler.java:45)
               at com.github.scribejava.httpclient.apache.OAuthAsyncCompletionHandler.completed(OAuthAsyncCompletionHandler.java:21)
               at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)
               at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
               at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:442)
               at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.responseReceived(HttpAsyncRequestExecutor.java:315)
               at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:255)
               at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
               at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
               at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
               at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
               at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
               at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
               at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
               at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
               at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
               ... 1 common frames omitted
```
If handle null check in Class  OAuthAsyncCompletionHandler.java like below code this issue will fix.  
```HttpEntity  httpEntity = httpResponse.getEntity(); 
final Response response = new Response(statusLine.getStatusCode(), statusLine.getReasonPhrase(), headersMap, httpEntity != null ? httpEntity.getContent() : null);
```
or 
based status code we can set Response 
```
if (status code == 204) {
    final Response response = new Response(statusLine.getStatusCode(), statusLine.getReasonPhrase(), headersMap, null);
}
```
Please let me know if your required any other information.
Thank you
 Sai.

**Comment by kullfar** [comment]
Good point, thx. Will add the fix to the master

**Comment by kullfar** [comment]
Pushed to the master
https://github.com/scribejava/scribejava/commit/2bfe14f7bfbbb538ab234ebde3dc40ad8fce8b2e

**Comment by SainagNeelamPatnaik** [comment]
Hi kulfar,
when the scribejava-httpclient-apache 6.3.1 jar available in maven repository?

**Comment by kullfar** [comment]
Hi, I'm planning to make the release this friday.
