### ISSUE TITLE
Android 9 Error

### ISSUE THREAD

**Issue by urvish91** [scribejava/scribejava#899]
We have implemented Garmin Connect with OAuth1 using scribe java. but in android 9 it is not working and we are getting below error.

Caused by java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/bind/DatatypeConverter;
       at com.github.scribejava.core.services.DatatypeConverterEncoder.encode(DatatypeConverterEncoder.java:9)
       at com.github.scribejava.core.services.HMACSha1SignatureService.bytesToBase64String(HMACSha1SignatureService.java:47)
       at com.github.scribejava.core.services.HMACSha1SignatureService.doSign(HMACSha1SignatureService.java:43)
       at com.github.scribejava.core.services.HMACSha1SignatureService.getSignature(HMACSha1SignatureService.java:31)
       at com.github.scribejava.core.oauth.OAuth10aService.getSignature(OAuth10aService.java:174)
       at com.github.scribejava.core.oauth.OAuth10aService.addOAuthParams(OAuth10aService.java:90)
       at com.github.scribejava.core.oauth.OAuth10aService.signRequest(OAuth10aService.java:149)
       at co.inteza.mmm.data.fit.managers.garmin.GarminImpl$readExerciseData$1.subscribe(GarminImpl.kt:214)
       at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
       at io.reactivex.Single.subscribe(Single.java:2703)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

Can you please help me to fix this ASAP.

**Comment by kullfar** [comment]
javax/xml/bind/DatatypeConverter etc was moved from java SE, beginning from 9 or so version. It can be the cause.
But... What version of ScribeJava you are using?
There is no such class DatatypeConverterEncoder in ScribeJava

**Comment by kullfar** [comment]
it was dropped in 5.1.0
I think you should just upgrade ScribeJava and all will be fine

**Comment by kullfar** [comment]
actual version is 6.3.0

**Comment by urvish91** [comment]
Yeah, thanks @kullfar It works fine after moving to 6.3.0. Highly appreciated your efforts.
