### ISSUE TITLE
Getting accessToken from Odnoklassniki with OkHttpHttpClientConfig.defaultConfig()

### ISSUE THREAD

**Issue by Lapter57** [scribejava/scribejava#965]
Hi! I tried to get an access token from Odnoklassniki and i used `OkHttpHttpClientConfig.defaultConfig()`. But the method `service.getAccessToken(code)` throwed exception:

```
'okhttp3.RequestBody okhttp3.RequestBody.create(byte[], okhttp3.MediaType)'
java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(byte[], okhttp3.MediaType)'
	at com.github.scribejava.httpclient.okhttp.OkHttpHttpClient$BodyType$1.createBody(OkHttpHttpClient.java:168)
	at com.github.scribejava.httpclient.okhttp.OkHttpHttpClient.createCall(OkHttpHttpClient.java:143)
	at com.github.scribejava.httpclient.okhttp.OkHttpHttpClient.doExecute(OkHttpHttpClient.java:126)
	at com.github.scribejava.httpclient.okhttp.OkHttpHttpClient.execute(OkHttpHttpClient.java:100)
	at com.github.scribejava.core.oauth.OAuthService.execute(OAuthService.java:114)
	at com.github.scribejava.core.oauth.OAuth20Service.sendAccessTokenRequestSync(OAuth20Service.java:46)
	at com.github.scribejava.core.oauth.OAuth20Service.getAccessToken(OAuth20Service.java:97)
	at com.github.scribejava.core.oauth.OAuth20Service.getAccessToken(OAuth20Service.java:92)
```

Then i changed `OkHttpHttpClientConfig.defaultConfig()`. to `ApacheHttpClientConfig.defaultConfig()` and everything was fine.

**Comment by kullfar** [comment]
Hi, @Lapter57!
I think your project had an old okhttp in dependencies.
Check your dependencies please, and compare with Scribejava's okhttp version  https://github.com/scribejava/scribejava/blob/master/scribejava-httpclient-okhttp/pom.xml#L26
It's 4.9.0 for today. And it was around 4.6.0 in the day of your issue.

Anyway, can you reproduce it now?

Your stacktrace looks like in your project was an older okhttp connected.

If you have a maven project, run something like this:
```mvn dependency:tree | grep okhttp```
